server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: sucre-surena
  datasource:
    url: jdbc:postgresql://localhost:5432/planillas
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      continue-on-error: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/La_Paz
  jackson:
    time-zone: America/La_Paz
    date-format: yyyy-MM-dd

app:
  jwt:
    secret: "SucreSurenaClaveSecretaParaFirmarTokensJWT2026CambiarEnProduccion"
    expiration-ms: 86400000

logging:
  level:
    org.hibernate.SQL: warn
    com.sucre: debug
